
root: /

Home: /
Archives: /archives
About: /about

language: en

author: Jenny Wu
description: Life is good!

disqus:
  enable: false
  shortname:

google_site_verification:
google_analytics:
